services:
  react:
    container_name: react
    env_file: .env
    build:
      context: .
      dockerfile: docker/react/Dockerfile
    volumes:
      - ./app/react:/app

  php:
    container_name: php
    env_file: .env
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: dev
    volumes:
      - ./app/php:/app

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    ports:
      - "443:443"
      - "8000:8000"
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./app/php:/app
    depends_on:
      - react
      - php
    networks:
      - default

networks:
  default:
    driver: bridge
