services:
  react:
    container_name: react
    env_file: .env
    build:
      context: .
      dockerfile: docker/react/Dockerfile
    volumes:
      - ./app/react:/app
    networks:
      - app-network

  php:
    container_name: php
    env_file: .env
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: dev
    volumes:
      - ./app/php:/app
    depends_on:
      - database
    networks:
      - app-network
      - database-network

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    env_file: .env
    environment:
      - BACKEND_URL=${BACKEND_URL:-api.localhost}
      - FRONTEND_URL=${FRONTEND_URL:-localhost}
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./app/php:/app
    depends_on:
      - react
      - php
    networks:
      - app-network

  database:
    image: mysql:8.4
    restart: unless-stopped
    container_name: database
    env_file: .env
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - database:/var/lib/mysql
    networks:
      - database-network

networks:
  app-network:
    driver: bridge
  database-network:
    driver: bridge

volumes:
  database:
