version: "3"

vars:
  DOCKER_COMPOSE: docker compose
  DOCKER_RUN: "{{.DOCKER_COMPOSE}} run --rm"

includes:
  caddy: ./taskfiles/caddy.yml
  deno:
    taskfile: ./taskfiles/deno.yml
    aliases: [client, react]
  dev: ./taskfiles/dev.yml
  docker: ./taskfiles/docker.yml
  env:
    taskfile: ./taskfiles/env.yml
  mysql:
    taskfile: ./taskfiles/mysql.yml
    aliases: [db, database]
  php:
    taskfile: ./taskfiles/php.yml
    aliases: [api, symfony]

dotenv: [.env]

set: [pipefail]
output: prefixed

tasks:
  default:
    cmds:
      - echo "Enter 'task --list' to see all available tasks"
    silent: true
