version: "3"

vars:
  DOCKER_COMPOSE: docker-compose
  DOCKER_RUN: "{{.DOCKER_COMPOSE}} run --rm"

includes:
  caddy: ./tasks/caddy.yml
  mysql:
    taskfile: ./tasks/mysql.yml
    aliases: [db, database]
  deno:
    taskfile: ./tasks/deno.yml
  docker:
    taskfile: ./tasks/docker.yml
    aliases: [dc]
  php: ./tasks/php.yml
  tools:
    taskfile: ./tasks/tools.yml

dotenv: [.env]

set: [pipefail]
output: prefixed

tasks:
  default:
    cmds:
      - echo "Enter 'task --list' to see all available tasks"
    silent: true

  install:
    desc: Initialize the complete stack
    cmds:
      - task: tools:env
      - task: mysql:init
      - task: php:init
      - task: deno:init
      - task: caddy:init
      - echo "✨ Installation complete! ✨"
    silent: true
