version: "3"

tasks:
  install:
    desc: Install Composer dependencies in PHP container
    cmds:
      - "{{.DOCKER_RUN}} php composer install"
    silent: true

  require:
    desc: Add a Composer package (task composer:require -- <package>)
    cmds:
      - |
        {{.DOCKER_RUN}} php composer require "{{.CLI_ARGS}}"
    silent: true

  require:dev:
    desc: Add a Composer development package (task composer:require-dev -- <package>)
    cmds:
      - |
        {{.DOCKER_RUN}} php composer require --dev "{{.CLI_ARGS}}"
    silent: true
