version: "3"

vars:
  ENTRYPOINT: src/main.tsx

tasks:
  default:
    desc: Run the 'deno:init' task
    cmds:
      - task: init
    silent: true

  add:
    desc: Add a new Deno dependency (task deno:add -- <package>)
    cmds:
      - "{{.DOCKER_RUN}} deno deno add {{.CLI_ARGS}}"
    silent: true

  remove:
    desc: Remove a Deno dependency (task deno:remove -- <package>)
    cmds:
      - "{{.DOCKER_RUN}} deno deno remove {{.CLI_ARGS}}"
    silent: true

  install:
    desc: Install npm dependencies into node_modules and cache Deno modules
    cmds:
      - >
        {{.DOCKER_RUN}} deno 
        deno cache
        --node-modules-dir=auto 
        {{.ENTRYPOINT}}
    silent: true

  dev:
    desc: Run development server
    cmds:
      - "{{.DOCKER_RUN}} -p 5173:5173 deno deno task dev --host"
    silent: true

  init:
    desc: Initialize Deno container
    cmds:
      - task: build
      - task: install
      - task: up
    silent: true

  build:
    desc: Build Deno container
    cmds:
      - "{{.DOCKER_COMPOSE}} build --no-cache deno"
    silent: true

  up:
    desc: Start Deno container
    cmds:
      - "{{.DOCKER_COMPOSE}} up -d deno"
    silent: true

  lint:
    desc: Lint with 'deno lint' command
    cmds:
      - "{{.DOCKER_RUN}} deno deno lint {{.CLI_ARGS}}"
    silent: true

  format:
    aliases:
      - fmt
    desc: Format with 'deno fmt' command
    cmds:
      - "{{.DOCKER_RUN}} deno deno fmt"
    silent: true

  clean-dependencies:
    desc: Clean Deno container
    cmds:
      - "{{.DOCKER_COMPOSE}} down --remove-orphans"
      - "{{.DOCKER_RUN}} deno rm -rf node_modules"
      - "{{.DOCKER_RUN}} deno rm -rf .vite"
    silent: true

  logs:
    desc: Show logs for Deno container
    cmds:
      - "{{.DOCKER_COMPOSE}} logs -f deno"
    silent: true

  shell:
    desc: Open a shell in the Deno container
    cmds:
      - "{{.DOCKER_RUN}} deno sh"
    silent: true
