version: "3"

tasks:
  default:
    desc: Check if mkcert is installed and generate certificates
    deps: [check]
    cmds:
      - |
        CLIENT_DOMAIN=$(echo "$CLIENT_URL" | sed -E 's|^"?https?://([^/]+).*"?$|\1|')
        API_DOMAIN=$(echo "$API_URL" | sed -E 's|^"?https?://([^/]+).*"?$|\1|')
        if [ ! -f config/certs/localhost.pem ] || [ ! -f config/certs/localhost-key.pem ]; then
          mkdir -p config/certs
          mkcert -install
          mkcert -key-file config/certs/localhost-key.pem -cert-file config/certs/localhost.pem "$CLIENT_DOMAIN" "$API_DOMAIN"
        else
          echo "Certificates already exist. Skipping generation."
        fi
    silent: true

  check:
    desc: Check if mkcert is installed
    cmds:
      - |
        if ! command -v mkcert > /dev/null; then
          echo "mkcert is not installed. Please install mkcert first."
        else
          echo "mkcert is installed."
        fi
    silent: true

  certs:
    desc: Check if certificates exist
    cmds:
      - |
        if [ ! -f config/certs/localhost.pem ] || [ ! -f config/certs/localhost-key.pem ]; then
          echo "Certificates do not exist. Run 'task mkcert' to generate them."
          exit 1
        else
          echo "Certificates exist."
        fi
    silent: true
