version: "3"

includes:
  composer: ./composer.yml

tasks:
  default:
    desc: Run the 'php:init' task
    cmds:
      - task: init
    silent: true

  init:
    desc: Initialize PHP container
    cmds:
      - task: build
      - task: composer:install
      - task: up
    silent: true

  build:
    desc: Build PHP container
    cmds:
      - "{{.DOCKER_COMPOSE}} build --no-cache php"
    silent: true

  up:
    desc: Start PHP container
    cmds:
      - "{{.DOCKER_COMPOSE}} up -d php"
    silent: true

  clean-dependencies:
    desc: Clean PHP container
    cmds:
      - "{{.DOCKER_RUN}} php rm -rf vendor/"
      - "{{.DOCKER_RUN}} php rm -rf var/cache/*"
    silent: true

  shell:
    desc: Open a shell in the PHP container
    cmds:
      - echo "PHP shell started. Press Ctrl+D to exit."
      - "{{.DOCKER_RUN}} php sh"
      - echo "PHP shell stopped."
    silent: true

  logs:
    desc: Show PHP container logs
    cmds:
      - "{{.DOCKER_COMPOSE}} logs -f php"
    silent: true

  console:
    desc: Run Symfony console command (task php:console -- <command>)
    cmds:
      - "{{.DOCKER_COMPOSE}} exec php php bin/console {{.CLI_ARGS}}"
    silent: true

  phpstan:
    desc: Run PHPStan
    cmds:
      - "{{.DOCKER_RUN}} php vendor/bin/phpstan analyse --memory-limit=512M {{.CLI_ARGS}}"
    silent: true

  cs-fixer:
    desc: Run PHP CS Fixer
    cmds:
      - "{{.DOCKER_COMPOSE}} exec -e PHP_CS_FIXER_IGNORE_ENV=1 php php vendor/bin/php-cs-fixer fix {{.CLI_ARGS}}"
    silent: true

  pest:
    aliases:
      - test
    desc: Run Pest tests
    cmds:
      - "{{.DOCKER_RUN}} php vendor/bin/pest --colors=always {{.CLI_ARGS}}"
    silent: true
