version: "3"

includes:
  composer: ./composer.yml

tasks:
  default:
    desc: Run the 'php:init' task
    cmds:
      - task: init
    silent: true

  init:
    desc: Initialize PHP container
    cmds:
      - task: build
      - task: composer:install
      - task: up
      - task: migrate
      - task: jwt:generate-keys:overwrite
      - task: fixtures:load
    silent: true

  build:
    desc: Build PHP container
    cmds:
      - "{{.DOCKER_COMPOSE}} build --no-cache php"
    silent: true

  up:
    desc: Start PHP container
    cmds:
      - "{{.DOCKER_COMPOSE}} up -d php"
    silent: true

  clean-dependencies:
    desc: Clean PHP container
    cmds:
      - "{{.DOCKER_RUN}} php rm -rf vendor/"
      - "{{.DOCKER_RUN}} php rm -rf var/cache/*"
    silent: true

  shell:
    desc: Open a shell in the PHP container
    cmds:
      - echo "PHP shell started. Press Ctrl+D to exit."
      - "{{.DOCKER_RUN}} php sh"
      - echo "PHP shell stopped."
    silent: true

  logs:
    desc: Show PHP container logs
    cmds:
      - "{{.DOCKER_COMPOSE}} logs -f php"
    silent: true

  console:
    desc: Run Symfony console command (task php:console -- <command>)
    cmds:
      - "{{.DOCKER_COMPOSE}} exec php php bin/console {{.CLI_ARGS}}"
    silent: true

  phpstan:
    desc: Run PHPStan
    cmds:
      - "{{.DOCKER_RUN}} php vendor/bin/phpstan analyse --memory-limit=512M {{.CLI_ARGS}}"
    silent: true

  cs-fixer:
    desc: Run PHP CS Fixer
    cmds:
      - "{{.DOCKER_COMPOSE}} exec -e PHP_CS_FIXER_IGNORE_ENV=1 php php vendor/bin/php-cs-fixer fix src/"
    silent: true

  pest:
    aliases:
      - test
    desc: Run Pest tests
    cmds:
      - "{{.DOCKER_RUN}} php vendor/bin/pest --colors=always {{.CLI_ARGS}}"
    silent: true

  cache:clear:
    desc: Clear Symfony cache
    cmds:
      - "{{.DOCKER_COMPOSE}} exec php bin/console cache:clear"
    silent: true

  migrations:migrate:
    desc: Run Symfony migrations
    aliases:
      - migrate
    cmds:
      - "{{.DOCKER_COMPOSE}} exec php bin/console doctrine:migrations:migrate --no-interaction"
    silent: true

  migrations:diff:
    desc: Show Symfony migration diff
    cmds:
      - "{{.DOCKER_COMPOSE}} exec php bin/console doctrine:migrations:diff --formatted"
    silent: true

  make:migration:
    desc: Create a new Symfony migration
    cmds:
      - "{{.DOCKER_COMPOSE}} exec php bin/console make:migration --formatted"
    silent: true

  fixtures:load:
    desc: Load Doctrine fixtures
    cmds:
      - "{{.DOCKER_COMPOSE}} exec php bin/console doctrine:fixtures:load --no-interaction"
    silent: true

  check:
    desc: Run Pest, PHPStan, and CS Fixer
    cmds:
      - task: cs-fixer
      - task: phpstan
      - task: pest
    silent: true

  jwt:generate-keys:
    desc: Generate JWT keys
    cmds:
      - "{{.DOCKER_COMPOSE}} exec php bin/console lexik:jwt:generate-keypair --skip-if-exists"
    silent: true

  jwt:generate-keys:overwrite:
    desc: Generate JWT keys (overwrite)
    cmds:
      - "{{.DOCKER_COMPOSE}} exec php bin/console lexik:jwt:generate-keypair --overwrite --no-interaction"
    silent: true