version: "3"

includes:
  composer: ./composer.yml

tasks:
  init:
    desc: Initialize PHP container
    cmds:
      - task: build
      - task: composer:install
      - task: up
    silent: true

  build:
    desc: Build PHP container
    cmds:
      - "{{.DOCKER_COMPOSE}} build --no-cache php"
    silent: true

  up:
    desc: Start PHP container
    cmds:
      - "{{.DOCKER_COMPOSE}} up -d php"
    silent: true

  clean:
    desc: Clean PHP container
    cmds:
      - "{{.DOCKER_RUN}} php rm -rf vendor/"
      - "{{.DOCKER_RUN}} php rm -rf var/cache/*"
    silent: true

  shell:
    desc: Open a shell in the PHP container
    cmds:
      - echo "PHP shell started. Press Ctrl+D to exit."
      - "{{.DOCKER_RUN}} php sh"
      - echo "PHP shell stopped"
    silent: true

  logs:
    desc: Show PHP container logs
    cmds:
      - "{{.DOCKER_COMPOSE}} logs -f php"
    silent: true
