version: "3"

tasks:
  env:
    desc: Create .env file from .env.example
    cmds:
      - |
        if [ ! -f .env ]; then
          cp .env.example .env
          SECRET=$(openssl rand -hex 16)
          if [ "$OSTYPE" = "darwin"* ]; then
            sed -i '' "s/^APP_SECRET=$/APP_SECRET=$SECRET/" .env
          else
            sed -i "s/^APP_SECRET=$/APP_SECRET=$SECRET/" .env
          fi
          echo "Created .env file from .env.example with new APP_SECRET"
        else
          echo ".env file already exists"
        fi
    silent: true
