version: "3"

includes:
  caddy: ./caddy.yml
  deno: ./deno.yml
  env: ./env.yml
  mysql: ./mysql.yml
  php: ./php.yml

tasks:
  install:
    desc: Initialize the complete stack for development
    cmds:
      - task: env:generate
        vars: { ENV_TYPE: dev }
      - task: env:init
      - task: mysql
      - task: php
      - task: deno
      - task: caddy
      - echo "✨ Installation complete! ✨"
      - echo "🚀 You can start shipping your code! 🚀"
    silent: true
