version: "3"

includes:
  caddy: ./caddy.yml
  deno: ./deno.yml
  env: ./tools.yml
  mysql: ./mysql.yml
  php: ./php.yml
  

tasks:
  install:
    desc: Initialize the complete stack
    cmds:
      - task: env:generate
        vars: { ENV_TYPE: prod }
      - task: env:generate-secret
      - task: env:generate-db-url
      - task: mysql
      - task: php
      - task: deno
      - task: caddy
      - echo "✨ Installation complete! ✨"
    silent: true