nelmio_cors:
    defaults:
        allow_origin: ['%env(CLIENT_URL)%']
        allow_credentials: true
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE', 'PATCH']
        expose_headers: ['Link', 'Authorization']
        max_age: 3600
    paths:
        '^/': ~
