nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CLIENT_URL)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['*']
        expose_headers: ['*']
        max_age: 3600
    paths:
        '^/': null
